/// Flutter icons PavlokIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PavlokIcons
///      fonts:
///       - asset: fonts/PavlokIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PavlokIcons {
  PavlokIcons._();

  static const _kFontFam = 'PavlokIcons';
  static const String? _kFontPkg = null;

  static const IconData bolt = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bulb = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData donate = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData leaf = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sleep = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData walk = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData water = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
